services:
  - type: web
    name: tunca-kingroyal-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 --bind 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: RENDER_ENVIRONMENT
        value: "true"
      - key: PORT
        value: "10000"
      - key: DISPLAY
        value: ":99" 