services:
  - type: web
    name: tunca-kingroyal-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: RENDER_ENVIRONMENT
        value: "true"
      - key: PORT
        value: "10000"
      - key: DISPLAY
        value: ":99" 